UNIQUE_FIELDS = {
        "resampled_location": [],
        "question_stop_locations": [],
	"app_usage_statistics": [],
	"dk_dtu_compute_facebook": [],
	"dk_dtu_compute_questionnaire": ["form_version", "response", "user", "variable_name"],
	"edu_mit_media_funf_probe_builtin_BluetoothProbe": ["bt_mac", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_CallLogProbe": ["number", "type", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_CellProbe": ["cid", "lac", "psc", "type", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_ContactProbe": ["mimetype", "contact_id", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_HardwareInfoProbe": ["android_id", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_LocationProbe": ["lat", "lon", "provider", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_ScreenProbe": ["screen_on", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_SMSProbe": ["type", "body", "address", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_TimeOffsetProbe": ["time_offset", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_WifiProbe": ["bssid", "level", "timestamp", "user"],
	"edu_mit_media_funf_probe_builtin_ExperienceSamplingProbe": [],
	"edu_mit_media_funf_probe_builtin_EpidemicProbe": [],
	"edu_mit_media_funf_probe_builtin_AndroidInfoProbe": ['build_number', 'user', 'timestamp'],
	"edu_mit_media_funf_probe_builtin_ActivityRecognitionProbe": ['user', 'timestamp', 'confidence', 'activity'],
	"data_quality": []
}
