from django.http import HttpResponse
import bson.json_util as json
from authorization_manager import authorization_manager
from utils import database
from django.shortcuts import render_to_response
from accounts.models import UserRole
from django.contrib.auth.models import User

def questionnaire(request):
	decrypted = booleanize(request.REQUEST.get('decrypted', False))

	if decrypted:
		return questionnaireDecrypted(request)
	else:
		return questionnaireEncrypted(request)






def questionnaireDecrypted(request):

	#TODO: actually this should be all_data and all_data_decrypted scopes
	accepted_scopes = set(['connector_raw.all_data', 'connector_raw.all_data_encrypted'])

	auth = authorization_manager.authenticate_token(request)
	if 'error' in auth:
		return HttpResponse(json.dumps(auth), status=401)
	
	auth_scopes = set([x for x in auth['scope']])

	if len(accepted_scopes & auth_scopes) == 0:
		return HttpResponse(json.dumps({'error':'token not authorized for any accepted scope %s'%str(list(accepted_scopes))}), status=401)


	#TODO: parameters: user (if can be any), time, etc.

	users_to_return = buildUsersToReturn(auth['user'], request)
	db = database.Database()
	docs = db.getDocuments(query={'user': {'$in': users_to_return}}, collection='dk_dtu_compute_questionnaire')

	#TODO we are not encrypting the responses in this collection, so we don't have to decrypt, but we should still add the anonymizer method, just because

	pretty = booleanize(request.REQUEST.get('pretty', False))

	if pretty:
		return render_to_response('pretty_json.html', {'response': json.dumps(docs, indent=2)})
	else:
		return HttpResponse(json.dumps(docs))



def questionnaireEncrypted(request):
	return HttpResponse('hello')

#This is simple rule matching to return all users if the token has been generated by a researcher role
#Otherwise return user's own data
def buildUsersToReturn(auth_user, request):
	users_to_return = []
	roles = []
	try: roles = [x.role for x in UserRole.objects.get(user=auth_user).roles.all()]
	except: pass
	if 'researcher' in roles:
		users_to_return = [x.username for x in User.objects.filter().all()]
	else:
		users_to_return.append(auth_user.username)
	return users_to_return


def booleanize(string):
	if string == False: return False
	if string == True: return True
	if string == 'True': return True
	if string == 'true': return True
	return False
